---
- name: Install MongoDB community edition with 2 Replicator and 1 Arbiter
  hosts: mongodb
  vars:
    repl_name: "rs0"
    members:
      - host: "mongodb1"
        port: "27017"
        arbiter: false
      - host: "mongodb2"
        port: "27017"
        arbiter: false
      - host: "mongodb3"
        port: "27017"
        arbiter: true
  tasks:
    - name: Import MongoDB package repository key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-6.0.asc
        state: present
      become: true
    
    - name: Add MongoDB package repository
      apt_repository:
        repo: 'deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse'
        state: present
        update_cache: yes
      become: true

    #This is needed for Ubuntu 20.04 as libssl1.1 is not included but it is needed for mongoDB6.0.
    - name: Add Security package repository
      apt_repository:
        repo: 'deb [ arch=amd64 ] http://security.ubuntu.com/ubuntu focal-security main'
        state: present
        update_cache: yes
      become: true
    
    - name: Install libssl1.1 dependency
      apt:
        name: libssl1.1
        state: present
      become: true

    - name: Install MongoDB community edition
      package:
        name: mongodb-org
        state: present
      become: true
    
    - name: Start MongoDB service with replication enabled
      shell: systemctl start mongod
      become: true

    - name: Wait for MongoDB to start
      pause:
        seconds: 20
    
    - name: Add replication configuration to mongod.conf
      lineinfile:
        path: /etc/mongod.conf
        regexp: '^replication:'
        line: 'replication: { replSetName: "{{ repl_name }}" }'
        state: present
      become: true

    - name: Configure MongoDB Community Edition Replicaset
      command: mongod --replSet {{ repl_name }} --bind_ip {{ hostvars[item].ansible_eth0.ipv4.address }} --port {{ item.port }} 
      with_items: "{{ members }}"
      loop_control:
        loop_var: item

    - name: Configure Replicaset
      shell:  mongosh --eval 'rs.initiate({ _id: "{{ repl_name }}", members: [ { _id: 0, host: "mongodb1:27017" },{ _id: 1, host: "mongod2:27017" }] });'

    - name: Wait for replica set initialization
      pause:
        seconds: 30

    - name: Add arbiter to replica set
      command: mongo --eval 'rs.addArb("{{ item.hostname }}:{{ item.port }}");'
      when: item.arbiter
      with_items: "{{ members }}"
      loop_control:
        loop_var: item

