---
- name: Install MongoDB community edition
  hosts: mongodb
  vars:
    repl_name: "rs0"
    members:
      - host: "mongodb1"
        priority: 1
        votes: 1
      - host: "mongodb2"
        priority: 1
        votes: 1
      - host: "mongodb3"
        priority: 0
        votes: 0
  tasks:
    - name: Import MongoDB package repository key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-6.0.asc
        state: present
    
    - name: Add MongoDB package repository
      apt_repository:
        repo: 'deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse'
        state: present
        update_cache: yes

    - name: Install MongoDB community edition
      package:
        name: mongodb-org
        state: present
      become: true
    - name: Start MongoDB service
      service:
        name: mongod
        state: started
        enabled: true
      become: true
    - name: Configure MongoDB replica set
      shell: |
        mongo --eval "rs.initiate({
          _id: '{{ repl_name }}',
          members: [
            { _id: 0, host: '{{ members[0].host }}:27017', priority: {{ members[0].priority }}, votes: {{ members[0].votes }} },
            { _id: 1, host: '{{ members[1].host }}:27017', priority: {{ members[1].priority }}, votes: {{ members[1].votes }} },
            { _id: 2, host: '{{ members[2].host }}:27017', priority: {{ members[2].priority }}, votes: {{ members[2].votes }} }
          ]
        })"
      become: true
    - name: Wait for replica set initialization
      pause:
        seconds: 30
    - name: Add arbiter to replica set
      shell: |
        mongo --eval "rs.addArb('{{ members[2].host }}:27017')"
      become: true

